name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: 
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore: 
      - "README.md"
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test ./tests/UrlShortener.Application.Integration.Tests/UrlShortener.Application.Integration.Tests.csproj --no-build
